# version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: eventzen-db
    env_file:
      - ./eventzen/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: ./eventzen
    container_name: eventzen-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./eventzen/.env

  frontend:
    build: ./frontend
    container_name: eventzen-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: