spring.application.name=eventzen
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EVENTZEN;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Eventzen@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always



jwt.secret=eventzensecretkey-capstone-project-deadline-monday
jwt.expiration=86400000