 spring.application.name=eventzen
 spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EVENTZEN;encrypt=false
 spring.datasource.username=sa
 spring.datasource.password=Eventzen@123

 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true
 spring.sql.init.mode=always

#spring.datasource.url=jdbc:sqlserver://db:1433;databaseName=EVENTZEN;encrypt=false;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=Adrita@123
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=never

jwt.secret=eventzensecretkey-capstone-project-deadline-monday
jwt.expiration=86400000